Bookstore/Controllers/Book1Controller.cs
using Bookstore.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookstore.Filters;


namespace Bookstore.Controllers
{
    [MyAuthorize]
    public class Book1Controller : Controller
    {

        private BookService _service;
        public Book1Controller()
        {
            //_service = new BookService(new BookDBRepository());
            //_service = new BookService(new BookTxtRepository());
            _service = new BookService();
        }

        // GET: Book
        public ActionResult Index()
        {
            return View();
        }
               
        public ActionResult Create()
        {          
            return View();
        }

        public ActionResult Details(int id)
        {
            ViewBag.id = id;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.id = id;
            return View();
        }

        public ActionResult Delete(int id)
        {
            ViewBag.id = id;            
            return View();
        }


        // Web api---
        [HttpPost]
        public JsonResult GetAllBooks()
        {
            var ret = _service.GetAll();
            return Json(ret);
        }

        [HttpPost]
        public JsonResult GetBook(int id)
        {
            var ret = _service.Get(id);
            return Json(ret);
        }

        [HttpPost]
        public bool CreateBook(Book book)
        {           
            bool ret = _service.Insert(book);
            return ret;
        }


        [HttpPost]
        public bool UpdateBook(Book book)
        {
            var ret = _service.Update(book);
            return ret;
        }

        [HttpPost]
        public bool DeleteBook(int id)
        {
            var ret = _service.Delete(id);
            return ret;
        }


        protected override void Dispose(bool disposing)
        {
            _service.Dispose();
            base.Dispose(disposing);
        }
    }
}

Bookstore/Controllers/BookController.cs
using Bookstore.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bookstore.Controllers
{
    public class BookController : Controller
    {

        private BookService _service;
        public BookController()
        {
            //_service = new BookService(new BookDBRepository());
            //_service = new BookService(new BookTxtRepository());
            _service = new BookService();
        }


        // GET: Book
        public ActionResult Index()
        {
            var ret = _service.GetAll();
            return View(ret);
        }



        public ActionResult Create()
        {          
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book)
        {
            if (!ModelState.IsValid)
                return View();

            bool ret = _service.Insert(book);
            return RedirectToAction("Index");
        }


        public ActionResult Details(int id)
        {
            var ret = _service.Get(id);
            return View(ret);
        }

        public ActionResult Edit(int id)
        {
            var ret = _service.Get(id);
            return View(ret);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Book book)
        {
            if (!ModelState.IsValid) 
                return View();
            
            bool ret = _service.Update(book);
            return RedirectToAction("Index");

        }

        
        public ActionResult Delete(int id)
        {
            var ret = _service.Get(id);
            return View(ret);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string confirmButton)
        {
            var ret = _service.Delete(id);

            if (!ret) return View();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _service.Dispose();
            base.Dispose(disposing);
        }
    }
}

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="~/Content/Site.css">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <!--<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">-->
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Bookstore", "Index", "Book")</li>
                        </ul>*@
            <!--</div>
        </div>
    </div>-->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Reflection</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact", "Home")">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Book")">Bookstore</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Book1")">AngularBookstore</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@User.Identity.Name</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

Bookstore/Views/Shared/_LayoutAngularjs.cshtml
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <base href="@Url.Content("~/")" />
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="~/Content/Site.css">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Reflection</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact", "Home")">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Book1")">Bookstore</a>
                </li>
                @*<li class="nav-item">
                    <a class="nav-link" href="#">@User.Identity.Name</a>
                </li>*@
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/angular.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>